/**
 * Type definitions for database schema introspection and metadata.
 * 
 * This module contains interfaces and enums for representing database schemas,
 * including tables, views, procedures, relationships, constraints, and metadata
 * discovered through database introspection.
 */

// src/types/database-schema.types.ts

/**
 * Complete database schema representation.
 * 
 * This interface represents the full structure of a database discovered through
 * introspection, including all tables, views, procedures, relationships, and
 * metadata. It's generated by the DataSourceService.introspect method.
 * 
 * @interface DatabaseSchema
 * 
 * @property {string} databaseName - Name of the database
 * @property {DatabaseType} databaseType - Type of database (SQL Server, MySQL, PostgreSQL, etc.)
 * @property {string} [version] - Database version string
 * @property {Date} lastScanned - Timestamp when the schema was last introspected
 * @property {number} scanDuration - Duration of the introspection scan in milliseconds
 * @property {TableSchema[]} tables - Array of all tables in the database
 * @property {ViewSchema[]} [views] - Array of all views in the database
 * @property {ProcedureSchema[]} [procedures] - Array of stored procedures and functions
 * @property {ConstraintSchema[]} [globalConstraints] - Database-level constraints and indexes
 * @property {RelationshipSchema[]} relationships - Detected relationships between tables
 * @property {BusinessRuleSchema[]} [businessRules] - Custom business rules or metadata
 * @property {DatabaseStatistics} [statistics] - Statistics about the database (table counts, sizes, etc.)
 * 
 * @example
 * const schema: DatabaseSchema = {
 *   databaseName: 'Northwind',
 *   databaseType: DatabaseType.SQL_SERVER,
 *   version: '2019',
 *   lastScanned: new Date('2024-01-15T10:30:00Z'),
 *   scanDuration: 5430,
 *   tables: [...],
 *   views: [...],
 *   relationships: [...],
 *   statistics: { totalTables: 13, totalRows: 3000, ... }
 * };
 */
export interface DatabaseSchema {
  /** Name of the database */
  databaseName: string;
  /** Type of database (SQL Server, MySQL, PostgreSQL, etc.) */
  databaseType: DatabaseType;
  /** Database version string */
  version?: string;
  /** Timestamp when the schema was last introspected */
  lastScanned: Date;
  /** Duration of the introspection scan in milliseconds */
  scanDuration: number;
  /** Array of all tables in the database */
  tables: TableSchema[];
  /** Array of all views in the database */
  views?: ViewSchema[];
  /** Array of stored procedures and functions */
  procedures?: ProcedureSchema[];
  /** Database-level constraints and indexes */
  globalConstraints?: ConstraintSchema[];
  /** Detected relationships between tables */
  relationships: RelationshipSchema[];
  /** Custom business rules or metadata */
  businessRules?: BusinessRuleSchema[];
  /** Statistics about the database (table counts, sizes, etc.) */
  statistics?: DatabaseStatistics;
}

/**
 * Schema information for a database table.
 * 
 * Represents a single table in the database, including its columns, indexes,
 * constraints, triggers, and metadata. This is the primary structure used
 * for building queries and understanding database structure.
 * 
 * @interface TableSchema
 * 
 * @property {string} name - Table name in the database
 * @property {string} [schema] - Database schema name (e.g., 'dbo', 'public')
 * @property {string} [displayName] - User-friendly display name
 * @property {string} [description] - Description of the table's purpose
 * @property {TableType} type - Type of table (BASE_TABLE, VIEW, TEMPORARY, SYSTEM)
 * @property {boolean} isSystemTable - Whether this is a system table
 * @property {ColumnSchema[]} columns - Array of all columns in the table
 * @property {IndexSchema[]} [indexes] - Array of indexes on the table
 * @property {ConstraintSchema[]} [constraints] - Array of constraints on the table
 * @property {TriggerSchema[]} [triggers] - Array of triggers on the table
 * @property {number} [rowCount] - Approximate number of rows in the table
 * @property {number} [sizeInBytes] - Size of the table in bytes
 * @property {Date} [lastModified] - Last modification timestamp
 * @property {string} [category] - Business category (e.g., 'Customer Data', 'Financial', 'Inventory')
 * @property {string[]} [tags] - Tags for categorization and search
 * @property {boolean} [isArchived] - Whether the table is archived
 * @property {Record<string, any>[]} [sampleData] - Sample data rows for preview
 */
export interface TableSchema {
  /** Table name in the database */
  name: string;
  /** Database schema name (e.g., 'dbo', 'public') */
  schema?: string;
  /** User-friendly display name */
  displayName?: string;
  /** Description of the table's purpose */
  description?: string;
  /** Type of table (BASE_TABLE, VIEW, TEMPORARY, SYSTEM) */
  type: TableType;
  /** Whether this is a system table */
  isSystemTable: boolean;
  /** Array of all columns in the table */
  columns: ColumnSchema[];
  /** Array of indexes on the table */
  indexes?: IndexSchema[];
  /** Array of constraints on the table */
  constraints?: ConstraintSchema[];
  /** Array of triggers on the table */
  triggers?: TriggerSchema[];
  /** Approximate number of rows in the table */
  rowCount?: number;
  /** Size of the table in bytes */
  sizeInBytes?: number;
  /** Last modification timestamp */
  lastModified?: Date;
  /** Business category (e.g., 'Customer Data', 'Financial', 'Inventory') */
  category?: string;
  /** Tags for categorization and search */
  tags?: string[];
  /** Whether the table is archived */
  isArchived?: boolean;
  /** Sample data rows for preview */
  sampleData?: Record<string, any>[];
}

/**
 * Schema information for a database column.
 * 
 * Represents a single column in a database table, including its data type,
 * constraints, relationships, and metadata. This information is used for
 * query building, validation, and UI field selection.
 * 
 * @interface ColumnSchema
 * 
 * @property {string} name - Original database column name (e.g., "ProductID")
 * @property {string} [displayName] - User-friendly display name
 * @property {string} [description] - Description of the column's purpose
 * @property {string} dataType - Native database type (e.g., 'varchar', 'int', 'datetime2')
 * @property {FieldDataType} normalizedType - Normalized type for the application
 * @property {boolean} isNullable - Whether the column allows NULL values
 * @property {boolean} isPrimaryKey - Whether the column is part of the primary key
 * @property {boolean} isForeignKey - Whether the column is a foreign key
 * @property {boolean} isUnique - Whether the column has a unique constraint
 * @property {boolean} isAutoIncrement - Whether the column auto-increments
 * @property {boolean} isComputed - Whether the column is computed/generated
 * @property {number} [maxLength] - Maximum length for string/binary types
 * @property {number} [precision] - Precision for numeric types
 * @property {number} [scale] - Scale for decimal types
 * @property {any} [defaultValue] - Default value for the column
 * @property {ForeignKeyReference} [foreignKeyReference] - Foreign key relationship details
 * @property {number} ordinalPosition - Column position in the table (1-based)
 * @property {any[]} [sampleValues] - Sample values for UI preview
 * @property {number} [distinctValueCount] - Number of distinct values in the column
 * @property {string} [businessName] - Business-friendly name for the column
 * @property {string} [businessDescription] - Business description of the column
 * @property {string} [format] - Format hint (e.g., 'currency', 'percentage', 'phone-number')
 * @property {ColumnCategory} [category] - Business category of the column
 * @property {number} [nullPercentage] - Percentage of NULL values in the column
 * @property {number} [uniquePercentage] - Percentage of unique values in the column
 * @property {boolean} [isPersonalData] - Whether the column contains personal/sensitive data
 * @property {SensitivityLevel} [sensitivityLevel] - Data sensitivity classification
 */
export interface ColumnSchema {
  /** Original database column name (e.g., "ProductID") */
  name: string;
  /** User-friendly display name */
  displayName?: string;
  /** Description of the column's purpose */
  description?: string;
  /** Native database type (e.g., 'varchar', 'int', 'datetime2') */
  dataType: string;
  /** Normalized type for the application */
  normalizedType: FieldDataType;
  /** Whether the column allows NULL values */
  isNullable: boolean;
  /** Whether the column is part of the primary key */
  isPrimaryKey: boolean;
  /** Whether the column is a foreign key */
  isForeignKey: boolean;
  /** Whether the column has a unique constraint */
  isUnique: boolean;
  /** Whether the column auto-increments */
  isAutoIncrement: boolean;
  /** Whether the column is computed/generated */
  isComputed: boolean;
  /** Maximum length for string/binary types */
  maxLength?: number;
  /** Precision for numeric types */
  precision?: number;
  /** Scale for decimal types */
  scale?: number;
  /** Default value for the column */
  defaultValue?: any;
  /** Foreign key relationship details */
  foreignKeyReference?: ForeignKeyReference;
  /** Column position in the table (1-based) */
  ordinalPosition: number;
  /** Sample values for UI preview */
  sampleValues?: any[];
  /** Number of distinct values in the column */
  distinctValueCount?: number;
  /** Business-friendly name for the column */
  businessName?: string;
  /** Business description of the column */
  businessDescription?: string;
  /** Format hint (e.g., 'currency', 'percentage', 'phone-number') */
  format?: string;
  /** Business category of the column */
  category?: ColumnCategory;
  /** Percentage of NULL values in the column */
  nullPercentage?: number;
  /** Percentage of unique values in the column */
  uniquePercentage?: number;
  /** Whether the column contains personal/sensitive data */
  isPersonalData?: boolean;
  /** Data sensitivity classification */
  sensitivityLevel?: SensitivityLevel;
}

/**
 * Schema information for a database view.
 * 
 * Represents a database view, which is a virtual table based on a SQL query.
 * Views can be queried like tables but don't store data themselves.
 * 
 * @interface ViewSchema
 * 
 * @property {string} name - View name in the database
 * @property {string} [schema] - Database schema name (e.g., 'dbo', 'public')
 * @property {string} [displayName] - User-friendly display name
 * @property {string} [description] - Description of the view's purpose
 * @property {string} definition - SQL definition of the view
 * @property {boolean} isUpdatable - Whether the view is updatable (allows INSERT/UPDATE/DELETE)
 * @property {ColumnSchema[]} columns - Array of columns exposed by the view
 * @property {string[]} dependsOnTables - Array of table names this view depends on
 * @property {string[]} dependsOnViews - Array of view names this view depends on
 * @property {string} [category] - Business category
 * @property {string[]} [tags] - Tags for categorization
 */
export interface ViewSchema {
  /** View name in the database */
  name: string;
  /** Database schema name (e.g., 'dbo', 'public') */
  schema?: string;
  /** User-friendly display name */
  displayName?: string;
  /** Description of the view's purpose */
  description?: string;
  /** SQL definition of the view */
  definition: string;
  /** Whether the view is updatable (allows INSERT/UPDATE/DELETE) */
  isUpdatable: boolean;
  /** Array of columns exposed by the view */
  columns: ColumnSchema[];
  /** Array of table names this view depends on */
  dependsOnTables: string[];
  /** Array of view names this view depends on */
  dependsOnViews: string[];
  /** Business category */
  category?: string;
  /** Tags for categorization */
  tags?: string[];
}

/**
 * Schema information for a stored procedure or function.
 * 
 * Represents a database stored procedure or function, including its parameters
 * and return type. Procedures can be executed to perform operations or return data.
 * 
 * @interface ProcedureSchema
 * 
 * @property {string} name - Procedure/function name in the database
 * @property {string} [schema] - Database schema name (e.g., 'dbo', 'public')
 * @property {string} [displayName] - User-friendly display name
 * @property {string} [description] - Description of the procedure's purpose
 * @property {ProcedureType} type - Type of procedure (STORED_PROCEDURE, FUNCTION, TABLE_FUNCTION)
 * @property {ParameterSchema[]} parameters - Array of procedure parameters
 * @property {string} [returnType] - Return type (for functions)
 * @property {string} [category] - Business category
 * @property {boolean} [isReportProcedure] - Whether this procedure is used for report generation
 */
export interface ProcedureSchema {
  /** Procedure/function name in the database */
  name: string;
  /** Database schema name (e.g., 'dbo', 'public') */
  schema?: string;
  /** User-friendly display name */
  displayName?: string;
  /** Description of the procedure's purpose */
  description?: string;
  /** Type of procedure (STORED_PROCEDURE, FUNCTION, TABLE_FUNCTION) */
  type: ProcedureType;
  /** Array of procedure parameters */
  parameters: ParameterSchema[];
  /** Return type (for functions) */
  returnType?: string;
  /** Business category */
  category?: string;
  /** Whether this procedure is used for report generation */
  isReportProcedure?: boolean;
}

/**
 * Schema information for a procedure parameter.
 * 
 * Represents a parameter of a stored procedure or function.
 * 
 * @interface ParameterSchema
 * 
 * @property {string} name - Parameter name
 * @property {string} dataType - Native database data type
 * @property {FieldDataType} normalizedType - Normalized type for the application
 * @property {boolean} isOutput - Whether this is an output parameter
 * @property {boolean} isOptional - Whether the parameter is optional
 * @property {any} [defaultValue] - Default value for the parameter
 * @property {string} [description] - Description of the parameter
 */
export interface ParameterSchema {
  /** Parameter name */
  name: string;
  /** Native database data type */
  dataType: string;
  /** Normalized type for the application */
  normalizedType: FieldDataType;
  /** Whether this is an output parameter */
  isOutput: boolean;
  /** Whether the parameter is optional */
  isOptional: boolean;
  /** Default value for the parameter */
  defaultValue?: any;
  /** Description of the parameter */
  description?: string;
}

/**
 * Schema information for a database index.
 * 
 * Represents an index on a table, which improves query performance by
 * providing faster data access paths.
 * 
 * @interface IndexSchema
 * 
 * @property {string} name - Index name
 * @property {IndexType} type - Type of index (CLUSTERED, NON_CLUSTERED, UNIQUE, etc.)
 * @property {boolean} isUnique - Whether the index enforces uniqueness
 * @property {boolean} isPrimaryKey - Whether this is the primary key index
 * @property {boolean} isClustered - Whether this is a clustered index
 * @property {IndexColumnSchema[]} columns - Array of columns in the index
 * @property {number} [fillFactor] - Fill factor percentage (0-100)
 * @property {boolean} [isDisabled] - Whether the index is disabled
 * @property {number} [sizeInBytes] - Size of the index in bytes
 * @property {number} [rowCount] - Number of rows indexed
 * @property {Date} [lastUsed] - Last time the index was used in a query
 */
export interface IndexSchema {
  /** Index name */
  name: string;
  /** Type of index (CLUSTERED, NON_CLUSTERED, UNIQUE, etc.) */
  type: IndexType;
  /** Whether the index enforces uniqueness */
  isUnique: boolean;
  /** Whether this is the primary key index */
  isPrimaryKey: boolean;
  /** Whether this is a clustered index */
  isClustered: boolean;
  /** Array of columns in the index */
  columns: IndexColumnSchema[];
  /** Fill factor percentage (0-100) */
  fillFactor?: number;
  /** Whether the index is disabled */
  isDisabled?: boolean;
  /** Size of the index in bytes */
  sizeInBytes?: number;
  /** Number of rows indexed */
  rowCount?: number;
  /** Last time the index was used in a query */
  lastUsed?: Date;
}

/**
 * Schema information for a column in an index.
 * 
 * @interface IndexColumnSchema
 * 
 * @property {string} columnName - Name of the column in the index
 * @property {SortOrder} sortOrder - Sort order for this column (ASC or DESC)
 * @property {number} ordinalPosition - Position of this column in the index (1-based)
 * @property {boolean} [isIncludedColumn] - Whether this is an included column (non-key column in non-clustered index)
 */
export interface IndexColumnSchema {
  /** Name of the column in the index */
  columnName: string;
  /** Sort order for this column (ASC or DESC) */
  sortOrder: SortOrder;
  /** Position of this column in the index (1-based) */
  ordinalPosition: number;
  /** Whether this is an included column (non-key column in non-clustered index) */
  isIncludedColumn?: boolean;
}

/**
 * Schema information for a database constraint.
 * 
 * Represents a constraint on a table (primary key, foreign key, unique, check, etc.)
 * that enforces data integrity rules.
 * 
 * @interface ConstraintSchema
 * 
 * @property {string} name - Constraint name
 * @property {ConstraintType} type - Type of constraint (PRIMARY_KEY, FOREIGN_KEY, UNIQUE, CHECK, etc.)
 * @property {string} tableName - Name of the table this constraint belongs to
 * @property {string} definition - SQL definition of the constraint
 * @property {boolean} isEnabled - Whether the constraint is currently enabled
 * @property {string[]} columns - Array of column names involved in the constraint
 * @property {string} [referencedTable] - Referenced table (for foreign key constraints)
 * @property {string[]} [referencedColumns] - Referenced columns (for foreign key constraints)
 * @property {ReferentialAction} [onDeleteAction] - Action on delete (CASCADE, SET_NULL, etc.)
 * @property {ReferentialAction} [onUpdateAction] - Action on update (CASCADE, SET_NULL, etc.)
 */
export interface ConstraintSchema {
  /** Constraint name */
  name: string;
  /** Type of constraint (PRIMARY_KEY, FOREIGN_KEY, UNIQUE, CHECK, etc.) */
  type: ConstraintType;
  /** Name of the table this constraint belongs to */
  tableName: string;
  /** SQL definition of the constraint */
  definition: string;
  /** Whether the constraint is currently enabled */
  isEnabled: boolean;
  /** Array of column names involved in the constraint */
  columns: string[];
  /** Referenced table (for foreign key constraints) */
  referencedTable?: string;
  /** Referenced columns (for foreign key constraints) */
  referencedColumns?: string[];
  /** Action on delete (CASCADE, SET_NULL, etc.) */
  onDeleteAction?: ReferentialAction;
  /** Action on update (CASCADE, SET_NULL, etc.) */
  onUpdateAction?: ReferentialAction;
}

/**
 * Schema information for a database trigger.
 * 
 * Represents a database trigger that executes automatically when certain
 * events occur on a table.
 * 
 * @interface TriggerSchema
 * 
 * @property {string} name - Trigger name
 * @property {TriggerType} type - Type of trigger (DML, DDL, LOGON)
 * @property {TriggerEvent[]} events - Events that fire the trigger (INSERT, UPDATE, DELETE)
 * @property {TriggerTiming} timing - When the trigger fires (BEFORE, AFTER, INSTEAD_OF)
 * @property {string} definition - SQL definition of the trigger
 * @property {boolean} isEnabled - Whether the trigger is currently enabled
 */
export interface TriggerSchema {
  /** Trigger name */
  name: string;
  /** Type of trigger (DML, DDL, LOGON) */
  type: TriggerType;
  /** Events that fire the trigger (INSERT, UPDATE, DELETE) */
  events: TriggerEvent[];
  /** When the trigger fires (BEFORE, AFTER, INSTEAD_OF) */
  timing: TriggerTiming;
  /** SQL definition of the trigger */
  definition: string;
  /** Whether the trigger is currently enabled */
  isEnabled: boolean;
}

/**
 * Schema information for a relationship between tables.
 * 
 * Represents a relationship between two tables, typically discovered through
 * foreign key constraints, naming conventions, or data analysis. Used for
 * understanding data model structure and suggesting joins in queries.
 * 
 * @interface RelationshipSchema
 * 
 * @property {string} id - Unique identifier for the relationship
 * @property {string} name - Relationship name (usually the foreign key constraint name)
 * @property {string} parentTable - Parent/referenced table name
 * @property {string} childTable - Child/referencing table name
 * @property {ColumnMapping[]} columnMappings - Array of column mappings between tables
 * @property {RelationshipType} type - Type of relationship (FOREIGN_KEY, INFERRED, BUSINESS_RULE)
 * @property {RelationshipCardinality} cardinality - Cardinality (ONE_TO_ONE, ONE_TO_MANY, MANY_TO_MANY)
 * @property {boolean} isEnforced - Whether the relationship is enforced by a constraint
 * @property {number} confidence - Confidence level (0-1) that this is a real relationship
 * @property {DetectionMethod} detectionMethod - Method used to detect the relationship
 * @property {string} [displayName] - User-friendly display name
 * @property {string} [description] - Description of the relationship
 */
export interface RelationshipSchema {
  /** Unique identifier for the relationship */
  id: string;
  /** Relationship name (usually the foreign key constraint name) */
  name: string;
  /** Parent/referenced table name */
  parentTable: string;
  /** Child/referencing table name */
  childTable: string;
  /** Array of column mappings between tables */
  columnMappings: ColumnMapping[];
  /** Type of relationship (FOREIGN_KEY, INFERRED, BUSINESS_RULE) */
  type: RelationshipType;
  /** Cardinality (ONE_TO_ONE, ONE_TO_MANY, MANY_TO_MANY) */
  cardinality: RelationshipCardinality;
  /** Whether the relationship is enforced by a constraint */
  isEnforced: boolean;
  /** Confidence level (0-1) that this is a real relationship */
  confidence: number;
  /** Method used to detect the relationship */
  detectionMethod: DetectionMethod;
  /** User-friendly display name */
  displayName?: string;
  /** Description of the relationship */
  description?: string;
}

/**
 * Mapping between columns in a relationship.
 * 
 * @interface ColumnMapping
 * 
 * @property {string} parentColumn - Column name in the parent/referenced table
 * @property {string} childColumn - Column name in the child/referencing table
 */
export interface ColumnMapping {
  /** Column name in the parent/referenced table */
  parentColumn: string;
  /** Column name in the child/referencing table */
  childColumn: string;
}

/**
 * Foreign key reference information.
 * 
 * Details about a foreign key relationship, including the referenced table
 * and column, constraint name, and referential actions.
 * 
 * @interface ForeignKeyReference
 * 
 * @property {string} referencedTable - Name of the table being referenced
 * @property {string} referencedColumn - Name of the column being referenced
 * @property {string} constraintName - Name of the foreign key constraint
 * @property {ReferentialAction} onDeleteAction - Action to take when referenced row is deleted
 * @property {ReferentialAction} onUpdateAction - Action to take when referenced row is updated
 */
export interface ForeignKeyReference {
  /** Name of the table being referenced */
  referencedTable: string;
  /** Name of the column being referenced */
  referencedColumn: string;
  /** Name of the foreign key constraint */
  constraintName: string;
  /** Action to take when referenced row is deleted */
  onDeleteAction: ReferentialAction;
  /** Action to take when referenced row is updated */
  onUpdateAction: ReferentialAction;
}

/**
 * Schema information for a business rule.
 * 
 * Represents a custom business rule or data quality rule that applies to
 * the database schema. These rules can be used for validation and data quality checks.
 * 
 * @interface BusinessRuleSchema
 * 
 * @property {string} id - Unique identifier for the rule
 * @property {string} name - Rule name
 * @property {string} description - Description of the rule
 * @property {BusinessRuleType} type - Type of rule (DATA_VALIDATION, BUSINESS_LOGIC, SECURITY, PERFORMANCE)
 * @property {string[]} affectedTables - Array of table names affected by this rule
 * @property {string[]} affectedColumns - Array of column names affected by this rule
 * @property {string} rule - Rule definition or expression
 * @property {boolean} isActive - Whether the rule is currently active
 * @property {string} [validationQuery] - SQL query to validate the rule
 * @property {RuleSeverity} severity - Severity level if rule is violated
 */
export interface BusinessRuleSchema {
  /** Unique identifier for the rule */
  id: string;
  /** Rule name */
  name: string;
  /** Description of the rule */
  description: string;
  /** Type of rule (DATA_VALIDATION, BUSINESS_LOGIC, SECURITY, PERFORMANCE) */
  type: BusinessRuleType;
  /** Array of table names affected by this rule */
  affectedTables: string[];
  /** Array of column names affected by this rule */
  affectedColumns: string[];
  /** Rule definition or expression */
  rule: string;
  /** Whether the rule is currently active */
  isActive: boolean;
  /** SQL query to validate the rule */
  validationQuery?: string;
  /** Severity level if rule is violated */
  severity: RuleSeverity;
}

/**
 * Statistics about the database.
 * 
 * Aggregated statistics about the database schema, including counts,
 * sizes, data quality metrics, and performance indicators.
 * 
 * @interface DatabaseStatistics
 * 
 * @property {number} totalTables - Total number of tables in the database
 * @property {number} totalViews - Total number of views in the database
 * @property {number} totalProcedures - Total number of stored procedures and functions
 * @property {number} totalIndexes - Total number of indexes
 * @property {number} totalSizeInBytes - Total size of the database in bytes
 * @property {number} totalRows - Total number of rows across all tables
 * @property {number} tablesWithPrimaryKeys - Number of tables with primary keys
 * @property {number} tablesWithForeignKeys - Number of tables with foreign keys
 * @property {number} orphanedTables - Number of tables with no relationships (isolated tables)
 * @property {string[]} mostAccessedTables - Array of most frequently accessed table names
 * @property {string[]} [slowestQueries] - Array of slowest query patterns or queries
 */
export interface DatabaseStatistics {
  /** Total number of tables in the database */
  totalTables: number;
  /** Total number of views in the database */
  totalViews: number;
  /** Total number of stored procedures and functions */
  totalProcedures: number;
  /** Total number of indexes */
  totalIndexes: number;
  /** Total size of the database in bytes */
  totalSizeInBytes: number;
  /** Total number of rows across all tables */
  totalRows: number;
  /** Number of tables with primary keys */
  tablesWithPrimaryKeys: number;
  /** Number of tables with foreign keys */
  tablesWithForeignKeys: number;
  /** Number of tables with no relationships (isolated tables) */
  orphanedTables: number;
  /** Array of most frequently accessed table names */
  mostAccessedTables: string[];
  /** Array of slowest query patterns or queries */
  slowestQueries?: string[];
}

/**
 * Enums and supporting types for database schema representation.
 */

/**
 * Enumeration of supported database types.
 * 
 * @enum {DatabaseType}
 */
export enum DatabaseType {
  /** Microsoft SQL Server */
  SQL_SERVER = 'sqlserver',
  /** MySQL database */
  MYSQL = 'mysql',
  /** PostgreSQL database */
  POSTGRESQL = 'postgresql',
  /** Oracle database */
  ORACLE = 'oracle',
  /** SQLite database */
  SQLITE = 'sqlite'
}

/**
 * Enumeration of table types.
 * 
 * @enum {TableType}
 */
export enum TableType {
  /** Regular base table */
  BASE_TABLE = 'base_table',
  /** Database view */
  VIEW = 'view',
  /** Temporary table */
  TEMPORARY = 'temporary',
  /** System table */
  SYSTEM = 'system'
}

/**
 * Enumeration of normalized field data types.
 * 
 * Normalized data types used across the application for consistent
 * type handling regardless of the underlying database type.
 * 
 * @enum {FieldDataType}
 */
export enum FieldDataType {
  /** String/text data type */
  STRING = 'string',
  /** Numeric data type (floating point) */
  NUMBER = 'number',
  /** Integer data type (whole numbers) */
  INTEGER = 'integer',
  /** Decimal data type (fixed precision) */
  DECIMAL = 'decimal',
  /** Currency/money data type */
  CURRENCY = 'currency',
  /** Date data type (date only, no time) */
  DATE = 'date',
  /** DateTime data type (date and time) */
  DATETIME = 'datetime',
  /** Time data type (time only, no date) */
  TIME = 'time',
  /** Boolean data type (true/false) */
  BOOLEAN = 'boolean',
  /** Large text data type */
  TEXT = 'text',
  /** JSON data type */
  JSON = 'json',
  /** Binary data type */
  BINARY = 'binary',
  /** UUID/GUID data type */
  UUID = 'uuid'
}

/**
 * Enumeration of column categories for business classification.
 * 
 * @enum {ColumnCategory}
 */
export enum ColumnCategory {
  /** Identifier column (primary keys, unique identifiers) */
  IDENTIFIER = 'identifier',
  /** Descriptive column (names, descriptions, text) */
  DESCRIPTIVE = 'descriptive',
  /** Quantitative column (numbers, amounts, counts) */
  QUANTITATIVE = 'quantitative',
  /** Temporal column (dates, times, timestamps) */
  TEMPORAL = 'temporal',
  /** Categorical column (enums, statuses, types) */
  CATEGORICAL = 'categorical',
  /** Binary column (yes/no, true/false, flags) */
  BINARY = 'binary',
  /** Metadata column (timestamps, audit fields) */
  METADATA = 'metadata'
}

/**
 * Enumeration of data sensitivity levels.
 * 
 * Used for data classification and security purposes.
 * 
 * @enum {SensitivityLevel}
 */
export enum SensitivityLevel {
  /** Public data - no restrictions */
  PUBLIC = 'public',
  /** Internal data - company internal use */
  INTERNAL = 'internal',
  /** Confidential data - restricted access */
  CONFIDENTIAL = 'confidential',
  /** Restricted data - highly sensitive, strict access controls */
  RESTRICTED = 'restricted'
}

/**
 * Enumeration of procedure types.
 * 
 * @enum {ProcedureType}
 */
export enum ProcedureType {
  /** Stored procedure */
  STORED_PROCEDURE = 'stored_procedure',
  /** Scalar or table-valued function */
  FUNCTION = 'function',
  /** Table function (returns a table) */
  TABLE_FUNCTION = 'table_function'
}

/**
 * Enumeration of index types.
 * 
 * @enum {IndexType}
 */
export enum IndexType {
  /** Clustered index (data is physically ordered) */
  CLUSTERED = 'clustered',
  /** Non-clustered index (separate structure) */
  NON_CLUSTERED = 'non_clustered',
  /** Unique index */
  UNIQUE = 'unique',
  /** Full-text index */
  FULL_TEXT = 'full_text',
  /** Spatial index */
  SPATIAL = 'spatial'
}

/**
 * Enumeration of constraint types.
 * 
 * @enum {ConstraintType}
 */
export enum ConstraintType {
  /** Primary key constraint */
  PRIMARY_KEY = 'primary_key',
  /** Foreign key constraint */
  FOREIGN_KEY = 'foreign_key',
  /** Unique constraint */
  UNIQUE = 'unique',
  /** Check constraint */
  CHECK = 'check',
  /** Default constraint */
  DEFAULT = 'default',
  /** Not null constraint */
  NOT_NULL = 'not_null'
}

/**
 * Enumeration of trigger types.
 * 
 * @enum {TriggerType}
 */
export enum TriggerType {
  /** Data Manipulation Language trigger (INSERT, UPDATE, DELETE) */
  DML = 'dml',
  /** Data Definition Language trigger (CREATE, ALTER, DROP) */
  DDL = 'ddl',
  /** Logon trigger */
  LOGON = 'logon'
}

/**
 * Enumeration of trigger events.
 * 
 * @enum {TriggerEvent}
 */
export enum TriggerEvent {
  /** INSERT event */
  INSERT = 'insert',
  /** UPDATE event */
  UPDATE = 'update',
  /** DELETE event */
  DELETE = 'delete'
}

/**
 * Enumeration of trigger timing.
 * 
 * @enum {TriggerTiming}
 */
export enum TriggerTiming {
  /** Trigger fires before the event */
  BEFORE = 'before',
  /** Trigger fires after the event */
  AFTER = 'after',
  /** Trigger fires instead of the event */
  INSTEAD_OF = 'instead_of'
}

/**
 * Enumeration of relationship types.
 * 
 * @enum {RelationshipType}
 */
export enum RelationshipType {
  /** Relationship enforced by foreign key constraint */
  FOREIGN_KEY = 'foreign_key',
  /** Relationship inferred from naming conventions or data patterns */
  INFERRED = 'inferred',
  /** Relationship defined by business rule */
  BUSINESS_RULE = 'business_rule'
}

/**
 * Enumeration of relationship cardinality.
 * 
 * @enum {RelationshipCardinality}
 */
export enum RelationshipCardinality {
  /** One-to-one relationship */
  ONE_TO_ONE = 'one_to_one',
  /** One-to-many relationship */
  ONE_TO_MANY = 'one_to_many',
  /** Many-to-many relationship */
  MANY_TO_MANY = 'many_to_many'
}

/**
 * Enumeration of relationship detection methods.
 * 
 * @enum {DetectionMethod}
 */
export enum DetectionMethod {
  /** Detected from foreign key constraint */
  FOREIGN_KEY_CONSTRAINT = 'foreign_key_constraint',
  /** Detected from naming conventions */
  NAMING_CONVENTION = 'naming_convention',
  /** Detected through data analysis */
  DATA_ANALYSIS = 'data_analysis',
  /** Manually defined */
  MANUAL = 'manual'
}

/**
 * Enumeration of referential actions for foreign keys.
 * 
 * Defines what happens when a referenced row is deleted or updated.
 * 
 * @enum {ReferentialAction}
 */
export enum ReferentialAction {
  /** No action taken (database default) */
  NO_ACTION = 'no_action',
  /** Cascade the action to related rows */
  CASCADE = 'cascade',
  /** Set foreign key to NULL */
  SET_NULL = 'set_null',
  /** Set foreign key to default value */
  SET_DEFAULT = 'set_default',
  /** Restrict the action (prevent if related rows exist) */
  RESTRICT = 'restrict'
}

/**
 * Enumeration of business rule types.
 * 
 * @enum {BusinessRuleType}
 */
export enum BusinessRuleType {
  /** Data validation rule */
  DATA_VALIDATION = 'data_validation',
  /** Business logic rule */
  BUSINESS_LOGIC = 'business_logic',
  /** Security rule */
  SECURITY = 'security',
  /** Performance rule */
  PERFORMANCE = 'performance'
}

/**
 * Enumeration of rule severity levels.
 * 
 * @enum {RuleSeverity}
 */
export enum RuleSeverity {
  /** Informational message */
  INFO = 'info',
  /** Warning level */
  WARNING = 'warning',
  /** Error level */
  ERROR = 'error',
  /** Critical level */
  CRITICAL = 'critical'
}

/**
 * Enumeration of sort order directions.
 * 
 * @enum {SortOrder}
 */
export enum SortOrder {
  /** Ascending order (A-Z, 0-9) */
  ASC = 'asc',
  /** Descending order (Z-A, 9-0) */
  DESC = 'desc'
}

// Example DatabaseSchema object
export const exampleDatabaseSchema: DatabaseSchema = {
  databaseName: 'northwind',
  databaseType: DatabaseType.SQL_SERVER,
  version: '2019',
  lastScanned: new Date('2024-01-15T10:30:00Z'),
  scanDuration: 5430, // 5.43 seconds
  
  tables: [
    {
      name: 'customers',
      schema: 'dbo',
      displayName: 'Customers',
      description: 'Customer master data',
      type: TableType.BASE_TABLE,
      isSystemTable: false,
      category: 'Customer Data',
      tags: ['master-data', 'crm'],
      rowCount: 91,
      sizeInBytes: 32768,
      lastModified: new Date('2024-01-10T14:22:00Z'),
      
      columns: [
        {
          name: 'customer_id',
          displayName: 'Customer ID',
          description: 'Unique identifier for customer',
          dataType: 'varchar',
          normalizedType: FieldDataType.STRING,
          isNullable: false,
          isPrimaryKey: true,
          isForeignKey: false,
          isUnique: true,
          isAutoIncrement: false,
          isComputed: false,
          maxLength: 5,
          ordinalPosition: 1,
          businessName: 'Customer Code',
          category: ColumnCategory.IDENTIFIER,
          sensitivityLevel: SensitivityLevel.INTERNAL,
          sampleValues: ['ALFKI', 'ANATR', 'ANTON'],
          distinctValueCount: 91,
          nullPercentage: 0,
          uniquePercentage: 100
        },
        {
          name: 'company_name',
          displayName: 'Company Name',
          description: 'Name of the customer company',
          dataType: 'varchar',
          normalizedType: FieldDataType.STRING,
          isNullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          isUnique: false,
          isAutoIncrement: false,
          isComputed: false,
          maxLength: 40,
          ordinalPosition: 2,
          businessName: 'Customer Name',
          category: ColumnCategory.DESCRIPTIVE,
          sensitivityLevel: SensitivityLevel.PUBLIC,
          sampleValues: ['Alfreds Futterkiste', 'Ana Trujillo Emparedados', 'Antonio Moreno Taquería'],
          distinctValueCount: 91,
          nullPercentage: 0,
          uniquePercentage: 100
        },
        {
          name: 'contact_name',
          displayName: 'Contact Name',
          dataType: 'varchar',
          normalizedType: FieldDataType.STRING,
          isNullable: true,
          isPrimaryKey: false,
          isForeignKey: false,
          isUnique: false,
          isAutoIncrement: false,
          isComputed: false,
          maxLength: 30,
          ordinalPosition: 3,
          category: ColumnCategory.DESCRIPTIVE,
          isPersonalData: true,
          sensitivityLevel: SensitivityLevel.CONFIDENTIAL,
          nullPercentage: 5,
          uniquePercentage: 95
        },
        {
          name: 'country',
          displayName: 'Country',
          dataType: 'varchar',
          normalizedType: FieldDataType.STRING,
          isNullable: true,
          isPrimaryKey: false,
          isForeignKey: false,
          isUnique: false,
          isAutoIncrement: false,
          isComputed: false,
          maxLength: 15,
          ordinalPosition: 4,
          category: ColumnCategory.CATEGORICAL,
          sensitivityLevel: SensitivityLevel.PUBLIC,
          sampleValues: ['Germany', 'Mexico', 'UK', 'Sweden'],
          distinctValueCount: 21,
          nullPercentage: 0
        }
      ],
      
      indexes: [
        {
          name: 'PK_customers',
          type: IndexType.CLUSTERED,
          isUnique: true,
          isPrimaryKey: true,
          isClustered: true,
          columns: [
            {
              columnName: 'customer_id',
              sortOrder: SortOrder.ASC,
              ordinalPosition: 1
            }
          ]
        }
      ],
      
      sampleData: [
        {
          customer_id: 'ALFKI',
          company_name: 'Alfreds Futterkiste',
          contact_name: 'Maria Anders',
          country: 'Germany'
        },
        {
          customer_id: 'ANATR',
          company_name: 'Ana Trujillo Emparedados y helados',
          contact_name: 'Ana Trujillo',
          country: 'Mexico'
        }
      ]
    },
    
    {
      name: 'orders',
      schema: 'dbo',
      displayName: 'Orders',
      description: 'Customer orders',
      type: TableType.BASE_TABLE,
      isSystemTable: false,
      category: 'Transaction Data',
      tags: ['transactions', 'sales'],
      rowCount: 830,
      
      columns: [
        {
          name: 'order_id',
          displayName: 'Order ID',
          dataType: 'int',
          normalizedType: FieldDataType.INTEGER,
          isNullable: false,
          isPrimaryKey: true,
          isForeignKey: false,
          isUnique: true,
          isAutoIncrement: true,
          isComputed: false,
          ordinalPosition: 1,
          category: ColumnCategory.IDENTIFIER
        },
        {
          name: 'customer_id',
          displayName: 'Customer ID',
          dataType: 'varchar',
          normalizedType: FieldDataType.STRING,
          isNullable: true,
          isPrimaryKey: false,
          isForeignKey: true,
          isUnique: false,
          isAutoIncrement: false,
          isComputed: false,
          maxLength: 5,
          ordinalPosition: 2,
          category: ColumnCategory.IDENTIFIER,
          foreignKeyReference: {
            referencedTable: 'customers',
            referencedColumn: 'customer_id',
            constraintName: 'FK_orders_customers',
            onDeleteAction: ReferentialAction.SET_NULL,
            onUpdateAction: ReferentialAction.CASCADE
          }
        },
        {
          name: 'order_date',
          displayName: 'Order Date',
          dataType: 'datetime',
          normalizedType: FieldDataType.DATETIME,
          isNullable: true,
          isPrimaryKey: false,
          isForeignKey: false,
          isUnique: false,
          isAutoIncrement: false,
          isComputed: false,
          ordinalPosition: 3,
          category: ColumnCategory.TEMPORAL,
          format: 'date'
        },
        {
          name: 'freight',
          displayName: 'Shipping Cost',
          dataType: 'money',
          normalizedType: FieldDataType.CURRENCY,
          isNullable: true,
          isPrimaryKey: false,
          isForeignKey: false,
          isUnique: false,
          isAutoIncrement: false,
          isComputed: false,
          precision: 19,
          scale: 4,
          ordinalPosition: 4,
          category: ColumnCategory.QUANTITATIVE,
          format: 'currency'
        }
      ]
    }
  ],
  
  relationships: [
    {
      id: 'customers_orders_rel',
      name: 'Customer Orders',
      parentTable: 'customers',
      childTable: 'orders',
      columnMappings: [
        {
          parentColumn: 'customer_id',
          childColumn: 'customer_id'
        }
      ],
      type: RelationshipType.FOREIGN_KEY,
      cardinality: RelationshipCardinality.ONE_TO_MANY,
      isEnforced: true,
      confidence: 1.0,
      detectionMethod: DetectionMethod.FOREIGN_KEY_CONSTRAINT,
      displayName: 'Customer to Orders',
      description: 'One customer can have many orders'
    }
  ],
  
  statistics: {
    totalTables: 13,
    totalViews: 3,
    totalProcedures: 7,
    totalIndexes: 25,
    totalSizeInBytes: 2097152,
    totalRows: 3000,
    tablesWithPrimaryKeys: 13,
    tablesWithForeignKeys: 8,
    orphanedTables: 0,
    mostAccessedTables: ['orders', 'customers', 'order_details']
  }
};